# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vsEZfETyr1_VV4JVxo8X_Dk2h7Szm0ie
"""

import kagglehub
path = kagglehub.dataset_download("heptapod/titanic")

import pandas as pd
import os

# List the contents of the 'path' directory to find the correct file name.
print(os.listdir(path))

# Assuming the file is named 'titanic.csv' and is directly under 'path',
# if not, we will adjust the path based on the output of os.listdir(path).
df = pd.read_csv(os.path.join(path, 'train_and_test2.csv'))

display(df.head(10))

mean_age = df['Age']
print(mean_age)

mean_fare =df['Fare'].mean()
print(mean_fare)



import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.hist(df['Age'], bins=20, edgecolor='black')
plt.title('Distribution of Age using Matplotlib')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)
plt.show()